package com.moveinsync.mobilitycopilot.metrics.domain;

public enum MetricId {
    M01_DELAYED_TRIP_RATE,
    M02_DELAY_MINUTES,
    M03_DELAY_REASON_MIX,
    M04_ON_TIME_PICKUP_RATE,
    M05_ON_TIME_DROP_RATE,
    M06_NO_SHOW_RATE,
    M07_DASHBOARD_CANCELLATION_RATE,
    M08_OCCUPANCY_RATE,
    M09_MEDIAN_COST_PER_TRIP,
    M10_COST_PER_BILLED_KM,
    M11_LOW_DRIVER_RATING_RATE,
    M12_MEAN_DRIVER_SAFETY_RATING,
    M13_ALERT_RATE,
    M14_SEVERE_ALERT_RATE,
    M15_SEVERE_ALERT_ACKNOWLEDGEMENT_P90,
    M16_TRACKING_GAP_RATE,
    M17_EV_SHARE,
    M18_ESCORT_PRESENT_RATE
}
