package com.moveinsync.mobilitycopilot.workflow.domain;

/** Target node catalog, not a claim that the sample engine executes all nodes. */
public enum WorkflowNode {
    INITIALIZE_RUN, AUTHORIZE_SCOPE, PROFILE_DATASET, BUILD_CAPABILITY_MATRIX,
    COMPUTE_METRIC_SNAPSHOT, DETECT_ANOMALIES, PRIORITIZE_ISSUE,
    SUPERVISOR_PLAN, VALIDATE_PLAN, RUN_INVESTIGATIONS, MERGE_EVIDENCE,
    EVIDENCE_CRITIC, VERIFY_EVIDENCE, COMPOSE_DECISION_BRIEF, ACTION_POLICY_GATE,
    APPROVAL_INTERRUPT, REVALIDATE_AND_EXECUTE_MOCK_ACTION, APPEND_AUDIT_EVENT
}
